name: create docker image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 拉取代码
      - name: Checkout repo
        uses: actions/checkout@v4
      # 构建 Docker 镜像
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag tools.shenzjd.com:v$(date +%d)
      # 创建docker文件夹
      - name: Create docker folder
        run: mkdir -p docker
      # 将镜像保存到docker文件夹
      - name: Save image
        run: docker save -o ./docker/tools.shenzjd.com-v$(date +%d).tar tools.shenzjd.com:v$(date +%d)
      # 上传到服务器
      - name: Upload to Deploy Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: "106.55.242.160"
          port: "21"
          local-dir: ./docker/
          username: tools_shenzjd_com
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
