name: ssh deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Triggering deployment using API endpoint
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{}' https://wallpaper.shenzjd.com/api/deploy
